# Generated by Django 4.2.5 on 2023-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comment', models.TextField()),
                ('price', models.IntegerField()),
                ('performance', models.TextField()),
                ('display', models.TextField()),
                ('battery', models.TextField()),
            ],
        ),
    ]
