# Generated by Django 4.2.5 on 2023-10-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='camera',
            field=models.TextField(null=True),
        ),
    ]
