# Generated by Django 4.2.5 on 2023-10-01 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0002_item_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='camera',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
